# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

CONFIG += c++17
INCLUDEPATH += \
$$PWD/src \
$$PWD/include

TR_EXCLUDE += \
$$PWD/src/* \
$$PWD/include/*

HEADERS += \
    $$PWD/gifLoad.h \
    $$PWD/gifdec.h

SOURCES += \
    $$PWD/gifLoad.cpp \
    $$PWD/gifdec.c

