# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

CONFIG += c++11
INCLUDEPATH += \
$$PWD/src \
$$PWD/include

HEADERS += \
    $$PWD/gifdec.h

SOURCES += \
    $$PWD/gifdec.c

