// ************************************************************************** //
//
//  Model-view-view-model framework for large GUI applications
//
//! @license   GNU General Public License v3 or higher (see COPYING)
//! @authors   see AUTHORS
//
// ************************************************************************** //

#ifndef SCRIPTS_TESTCONFIG_H
#define SCRIPTS_TESTCONFIG_H

#include <string>

//! Provides build time information for unit tests.
//! Automatically generated by CMake from testconfig.h.in

namespace TestConfig {

inline std::string CMakeSourceDir() { return "/Users/sea/thp/qt-mvvm"; }
inline std::string CMakeBinaryDir() { return "/Users/sea/thp/qt-mvvm/build"; }
inline std::string TestOutputDir() { return "/Users/sea/thp/qt-mvvm/build/test_output_mvvm"; }
inline std::string ProjectSourceDir() { return "/Users/sea/thp/qt-mvvm"; }
inline std::string TestData() { return "/Users/sea/thp/qt-mvvm/tests/data"; }

}

#endif

