# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


LIBS += -L$$PWD/lib  \
        -lspdlog

TR_EXCLUDE += $$PWD/include/*

INCLUDEPATH += \
$$PWD/include

HEADERS += \
    $$PWD/AWLogger.h \
    $$PWD/AWLoggerFactory.h \
    $$PWD/qt_sink.h

SOURCES += \
    $$PWD/AWLoggerFactory.cpp
